clc;
clear;
load('rawdata','-mat');
f_seq=S1(:,1);
c_seq=S1(:,2:end);
Names_X={'Financial Security Index',...
    'Deposit Growth Rate' 'Loan Growth Rate' 'Loan Ratio',...
    'NPL Ratio' 'Growth Rate of GDP' '(Nationwide) Inflation Rate',...
    'Growth of Household Consumption Rate' 'Unemployment Rate',...
    ['Growth Rate of Fixed Assets Investment',...
    newline,'in the Whole Society'],...
    'Real Estate Investment Growth Rate' 'Coal Investment Growth Rate',...
    'Total Import and Export Growth rate',...
    'Financial revenue growth rate' 'Industrial added value growth rate',...
    'Business efficiency (profit margin)' 'Coal revenue growth rate'};
years=(2006:2016);
line_S={'-','--',':','-.','-','--',':','-.','-','--',':','-.','-','--',':','-.','-'};
marker={'o','+','*','.','x','s','d','^','v','<','>','o','+','*','.','x','s'};
line_W={1.5,1.2,1.2,1.2,1.2,1.2,1.2,1.2,1.2,1.2,1.2,1.2,1.2,1.2,1.2,1.2,1.2};